pool:
  name: Default
  demands:
    - npm  # Ensure that npm is available on the agent
    - Agent.Version -gtVersion 2.182.1  # Ensure that the agent is at a version greater than 2.182.1

trigger:
  - master

steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Templates'
    inputs:
      SourceFolder: 'deployment'
      Contents: '*.json'
      TargetFolder: '$(build.artifactstagingdirectory)/Templates'

  - task: Npm@1
    displayName: 'npm custom'
    inputs:
      command: custom
      versionSpec: '6.x'  # Specify the NPM version (modify if necessary)
      verbose: false
      customCommand: 'install --production'

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
